Make the MaxConsumeCount  param configurable
dataddo/pgq pull request #4
Opened 2023-10-19 15:07 UTC by kedlas

2023-10-19 15:16 UTC, prochac commented
Let's use `uint`, negative values are useless here.
Also the merge should be synchronised with our update, as we rely on the former default value.

2023-10-19 15:20 UTC, kedlas commented
The merge sync is the reason why the default value is 3. I would prefer to have the default value 0 (disabled), but for that we must have all ourt consymers ready in advance. This change proposed does not change any configuration which we currently use.

2023-10-20 14:16 UTC, kedlas commented on consumer.go
> +	MaxConsumeCount:        3,
@prochac here is the default set to 3 not to bring any BC change

2023-10-20 14:17 UTC, kedlas commented on consumer.go
> +	MaxConsumeCount:        3,
it just makes the whole thing configurable without any BC change

2023-10-20 14:19 UTC, prochac commented
> The merge sync is the reason why the default value is 3. I would prefer to have the default value 0 (disabled), but for that we must have all ourt consymers ready in advance. This change proposed does not change any configuration which we currently use.

OK, let's migrate our code to explicitly use `3`, or better, make it configurable by env, and later we can make the breaking change, as it's only us using this module so far :D

2023-10-20 14:23 UTC, prochac requested changes

2023-10-20 14:23 UTC, prochac commented on consumer.go
> +// When message causes OOM it could lead to infinite loop in the consumers.
Not just OOM, any crash. Uncaught panic from `nil` pointer, SIGKILL, etc.

2023-10-20 14:23 UTC, prochac commented on consumer.go
> +	// This is a safety mechanism to prevent infinite loops when a message causes OOM errors
Again, not just OOM. Any crash.

2023-10-23 09:06 UTC, prochac approved these changes

2023-10-23 09:15 UTC, merged